# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    not_max_capacity_validator:
        class: AppBundle\Validator\Constraints\NotMaxCapacityValidator
        autowire: true
        tags:
            - { name : validator.constraint_validator }

    tarif_resolver:
        class: AppBundle\Service\TarifResolver
        autowire: true

    total_price_for_commande:
        class: AppBundle\Service\TotalPrice

    # Extension Twig pour convertir les codes régions des pays en noms
    app_twig_extension:
        class: Twig\AppExtension
        tags:
            - { name : twig.extension }

    send_mail:
        class: AppBundle\Service\SendMail
        autowire: true

    commande_checker:
        class: AppBundle\Service\CommandeChecker
        autowire: true

    commande_manager:
        class: AppBundle\Manager\CommandeManager

    stripe_api:
        class: AppBundle\Service\StripeAPI
